services:
  backend:
    build:
      context: ./backend/app
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    volumes:
      - ./backend/app/data:/app/data
    ports:
      - "8000:8000"
    expose:
      - "8000"
    networks:
      - app-network
    environment:
      - OPENAI_API_KEY=sk-xVDTvv4q702kF2VA1SPraYTLCOl1Oqvh2yY6e7fFZFT3BlbkFJbqvF4GRSa5vL3yscXAe_Ibw6ROlICyOhQt8Hq0D-YA
      - MONGODB_URI=mongodb+srv://alexpensotti:9Nae0ac14Fxhfk5A@moviewizard.unp4g.mongodb.net/mw_users?retryWrites=true&w=majority&appName=MovieWizard
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    expose:
      - "3000"
    networks:
      - app-network
    environment:
      - NEXT_PUBLIC_MWAPI=https://www.moviewizard.com/wizapi
      - NEXT_PUBLIC_OMBDAPI=https://www.omdbapi.com/?apikey=f523276c&plot=full  
      - GOOGLE_CLIENT_ID=543409743576-hji2c36frodkurna8b7hhp4agsc60i33.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - NEXTAUTH_SECRET=DNYs9V+PapNsy+kRVyxyzhbuDVHNVXn5GQArzgKHO1U=      
      - DATABASE_URL=postgresql://alex:asflkasjhajgla@localhost:5432/moviewizardusers?schema=public
      - NEXTAUTH_URL=https://moviewizard.com/api/auth
      

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
