version: '3.8'

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token eyJhIjoiZDMzOTg5ZGFmMTY5YzMwMWVkM2IxM2I4YzUwMDA4MzgiLCJ0IjoiMmVmMjRhOGYtMzgwMC00YTkyLTk2MTUtZGM3MzhmOTA3MjU1IiwicyI6Ik0yVTJZbVUwWmpFdE9UQmxPQzAwTkdJMUxXRmpNRE10TjJRNFpETTBNVEZpTkdSaSJ9
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
