import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div style={{ position: "fixed", top: "25px", left: "20px", zIndex: 100 }}>
          <div style={{ position: "relative", width: "100px", height: "100px" }}>
            <img
              src='/wizardlogo2xwhite.png'
              width={100}
              height={100}
              alt='logo'
              style={{
                position: "absolute",
                top: 0,
                left: 0,
                zIndex: 1,
                transition: "opacity 0.5s ease",
              }}
              className="fade-on-hover"
            />
            <img
              src='/wizardlogo2x.png'
              width={100}
              height={100}
              alt='logo'
              style={{ position: "absolute", top: 0, left: 0 }}
            />
          </div>
        </div>
        {/* Content */}
        {children}
      </body>
    </html>
  );
}
